[functions]
  directory = "netlify/functions"
  external_node_modules = ["mongodb"]
[[redirects]]
  from = "/search-playlists"
  to = "/.netlify/functions/search-playlists"
  status = 200
[dev]
  port = 3000
  staticServerPort = 3999