[functions]
  directory = "netlify/functions"
  external_node_modules = ["mongodb"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  port = 3001
  staticServerPort = 4000